language: node_js
node_js:
- '4.4'
env:
- SAUCE_USERNAME=verticalsol
before_install:
before_script:
- npm install
- npm install --save-dev chai karma karma-chai karma-chrome-launcher karma-coverage karma-firefox-launcher karma-html2js-preprocessor mocha karma-mocha karma-phantomjs-launcher karma-browserify babel-plugin-espower babelify karma-sauce-launcher
script:
- npm test
notifications:
  slack:
    secure: gnKw/BvuTAKFIxVwn0CtaEli4Md7NZPb3Pz0OqadzPv69jXKe1UehR1aunif6uae71Or1LqV19ez1/6JnjLjLpjQ0Zr4qmN+hY4mDNkuIToValGmsaRBqaB10JVzbgDvH2gZfucMdazpoPhNxbixRZw89hnm2psyJbm9nx2Ys9BGzu/F0D1+wIkVhsuLWf5NHUURSgSUvUvKuJtgX7HetbADbs5tqABGoKkBVhoWEyVKEn3TCKTczIaw2xFMXbt3KTFohlUM2wg2KqmbEHAZ1cbb6dWJM6chaLeBuBIv+HAjgWEz6kL8ongo8kvz2ip/x/xcrLfJXFC2tJjTHCVpYLmKhTWoVlAVBDKrEQEfDZTpbxUUO+BEAE7Fr+6RkNYdgdOqtVXLHaFRcbRUSUV+x7TJCKboZ06suKUFjzjZsHxST2xHDk8NNLcGr8e54SJl+44bgPRXTSStlNqf5ZQxS/bThgnb79nWgRc5eBxkbRThWRgnJwzSpAoDY2qWRcb+wtN/ct8mEvKNMCS+V4LZNdZbbk+77enZEeYBFgb7JcBrXZ3/xdUbNsKDRN66n2q8/O+cLKEjLQORd+43w1WoAMa/EL8kqOKQvu22Is6E0gyH0HiTHlY2rfm4hfyofD4yH8s1KbNk+tqQPQuHVaNTBl+8fOStHKUO0zJeHD4Kj9M=
addons:
  jwt:
    secure: lFhgKV2AgDpXv6rGY/VmShtXZ6WUVrctFA79okIjr8wF4uayaMlPWLDEVIXn8Db/ST/3CoKxzyuHJiwUKgC/9w3Up+VUO+SZ1NmbZwu+ryu9MW2SflrPqEq5/w1bWxU2krYphR5mDhaAVRKxDbJsOntuRI/v1D590vrzqUBqWDIrUMhGPJDKjL+N8TMhwQp2OTuuQbX0G869uLff9qSNNRnhI7b/lF8kjwxbEWXTx2JzX3g4KvQF5FBgy0+mvYIPhEew6pbvT8r8daT8VSqeozNPHpKUYuxLBExlMhxT48E/KtuJML0nyvp20glNql27oy7u3XlIPbKnEzeu0Hr8GtFcjlDUNvu6m3fFxMJTgY6tXX48n933uH4XwIaaRQuZMavuIsdoNhzAb60jlZBnLf+Lr25YSF6n6Z1qb7A8nh8M7laF1YoN5EP3iK9qc3Nh1hvsGTwBYlPzeoiIfEUEwpuJAyXE/hO9GpnIlfzDe2XbwBdB9PuKQyvyKq96OSBwh3P3gai/4OEN0nV+7xUxrv7W1ESvBd3CRQtqTxEYr/T+r7BpMvFvlgtvrEBzS4Q2cO+BJQkKp8yZpcBqm2y3xWNc0tzUDEQ2i5yttfCxyL+ldku6YSzRDYKt7XHqq+0jBSGAlI03MVXwhmS66vCXYk2GdV8db51+OuvMYslOMu8=
