language: node_js
node_js:
- '4.4'
env:
- SAUCE_USERNAME=opentok
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run build;
- npm test && bash <(curl -s https://codecov.io/bash);
- VER_DEPL=$(npm show opentok-annotation version);
- VERSION=$(jq '.version' package.json | sed -e 's/^"//' -e 's/"$//');
- if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" && "$VER_DEPL" != "$VERSION"]]; then
    git commit -m "New build. Bump npm version." --allow-empty;
    git tag v$VERSION;
    git push --quiet https://$GITHUBKEY@github.com/opentok/accelerator-annotation-js v$VERSION;
  fi
deploy:
  provider: npm
  email: vsolutions@tokbox.com
  api_key:
    secure: G265RoXVU02ru/nmUqDih7eSZVSNBAcggPsd18z7pVOPYXcYpDru2d2WHf1PxG37KEShQKrXNNw+Bg7vJP4JzGRDd9dsaxHmDVU8oOkHWB2ioeDzmAdK0sDuqhLC5A9z8KRf4fDVpQMAVIZ2yzIkv2KUPTZD9La+wDKgEsxxVFo6fpSoZOr967JLt2pRlgbCoV0wtuG4pr00uZvXvVoBXLYjYFxcLmeEH6Tv09aqpmL8EBTwmW8sApIUJZiw0PqvYrIN3q9Jl+EigegTfyoqfnwlm79fk1pTxM4bC21Quw5TAxwHZAFDYgiEN248FJhD1b/cSliWEcqZlKMC511ia64VE+72mg+PGU/7ZDT6Kbc99FpOzA+j17fr0BvgqjmMigu6eBZ3UiOK0wI1Vv7t/+8XaCKgDU3JJa7L8LZkizByGtJBNOgEO/5m6VnJcp8lwnihaF/5f3QL2y44irj0Oer5J+m97V4EJ6lJlWNpg1xDIkPjizCrECWE3O8JRgiFCQhN/tUxsD7XGAjDmw1EuroLpIHV66a+i94l3sRPWgUtvrMp+/I/6zMy/HV8cWCWW87qDLOUxJum1jZs9TdmyoS5i7OfxZfDLOy/MAhOcbUJqt6OXWR5AhrRGkrC/bqWktgEwGblkNYgNQ6U2WIo/WuP5nDx+0eK82jLFQnmGro=
  on:
    branch: master
    condition: $VERSION != $VER_DEPL
notifications:
  slack:
    secure: gnKw/BvuTAKFIxVwn0CtaEli4Md7NZPb3Pz0OqadzPv69jXKe1UehR1aunif6uae71Or1LqV19ez1/6JnjLjLpjQ0Zr4qmN+hY4mDNkuIToValGmsaRBqaB10JVzbgDvH2gZfucMdazpoPhNxbixRZw89hnm2psyJbm9nx2Ys9BGzu/F0D1+wIkVhsuLWf5NHUURSgSUvUvKuJtgX7HetbADbs5tqABGoKkBVhoWEyVKEn3TCKTczIaw2xFMXbt3KTFohlUM2wg2KqmbEHAZ1cbb6dWJM6chaLeBuBIv+HAjgWEz6kL8ongo8kvz2ip/x/xcrLfJXFC2tJjTHCVpYLmKhTWoVlAVBDKrEQEfDZTpbxUUO+BEAE7Fr+6RkNYdgdOqtVXLHaFRcbRUSUV+x7TJCKboZ06suKUFjzjZsHxST2xHDk8NNLcGr8e54SJl+44bgPRXTSStlNqf5ZQxS/bThgnb79nWgRc5eBxkbRThWRgnJwzSpAoDY2qWRcb+wtN/ct8mEvKNMCS+V4LZNdZbbk+77enZEeYBFgb7JcBrXZ3/xdUbNsKDRN66n2q8/O+cLKEjLQORd+43w1WoAMa/EL8kqOKQvu22Is6E0gyH0HiTHlY2rfm4hfyofD4yH8s1KbNk+tqQPQuHVaNTBl+8fOStHKUO0zJeHD4Kj9M=
addons:
  jwt:
    secure: Z+gEkV+OzmCpa7Ea74G8A2xZeymKsx2cRBOQE79yfGG7YJg/yG+EhhSg4XbPKGksy85P7Rb+cBbs48RfRwRyb64g5nCsOPfUwWB6Jp5d2WCXCl2FXWSfIu9lozRyOjSNbtqQiErE+fMN311eNN06bjhcDyH4DsBk5C5EigTYCN2zNusBuelc10N81Lt2bqzA7KZehw3ItJuBhnnSLSVIMDUdBxyrtJ7yHrkkXWJdmFnaalCnaNq+OovMZdFYMfoXzDFq2UUcnL4khjosVDhMQlpajuB2oLbCK8VBd8buh3/faEd5WOQRv1lJvVDnkMFnHgBXrDhHjJQeh8H1ht/ikR8e3bzJXpJMCXANXsWcxBDnA6J58B21fpiCcrJxzogzqg6IDfxkScOS1zPe4U79aCwoawfrnOgrA9ivmRVM3rvYSDJB2L3gAQKnIO2VUKb0W+le454Gi8YOfEslXrgWYVi3hiJLsWMKN6JyjRJLURTa6xQ9lvcsQeq9dVZeZF3G+wGLcOwdUupvV7tWI8pdn3j3B6b95972xoppT9Czy3hfGSS6bfhYTZQqixiTjBEUUsGYSYJ/op8NPIfxvbyGy5tpe7tK7Q/Oz12GbXAGe+1r7j6MKlWlIIFE6XMKMA3oNFP6AEwmiW7cD0uA5OcKjnF1vb4Lv1yXjX4axOhFTTw=
